# Generated by Django 3.2.10 on 2022-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='shirt', unique=True),
            preserve_default=False,
        ),
    ]
