# Generated by Django 3.2.10 on 2022-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220427_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_itens',
            field=models.ManyToManyField(related_name='order_itens', to='main_app.OrderItem'),
        ),
    ]
