# Generated by Django 3.2.10 on 2022-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_order_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_itens',
            field=models.ManyToManyField(to='main_app.OrderItem'),
        ),
    ]
